travis:
  secure:
    BINSTAR_TOKEN: KEwbV7RwZR3KotSHGOVthcX1IY/aMxzkQ+4Z63hjMiwPy3OlHL8+6z2kxe3als+mnVA66SOOGpwlFLvh0yKEEhsaSZH1RSy5n7DigLB+65i+xbZrSnr/XdS8+Lpi/gKnpgtwRij9RayOsgg3nvlv5N8cjxTEazeshMmql3Lhc0HuTvCS92LkdPihPMveEffMMJu2so70xufOspQ6bYeig0np1474jdcxIjCL8xGSyolf4BWus9EO0oOHF0cBAY0GxXy7fge1FA6EGvcSYLYfckk+75LolYuCR/2+G7nL2eo+kAS9VlkP569+KMA3ron5ZwBsMkL8FMw/+5WI+x75k5FC/xUL7/vvTGEcEhZY+bpYi1ov6FJuf+pjNK2RrQmj5udr/9/Jbtu8tAYt7NVC2k3jXkoTQc+JFoOIyR/cIZhVSE6vtA2WAzdBbS1jZ6ZXa2a0DmqBbed1ptaC9xeT4YjWeLeuKQIeVJhSTdH/xNSd9QfqYLerKbcE/lhg9w/9cnR2mU5YkOoM4BHmczgjzg5mhiaF+wmCepdgqqCL86hkgwEVCrFlo2vr+sKLjnSRYXLFzqL7mnVpxdINg6vmXCelB1XPgqQZck2suOHU7ZnNeayqbjlbMHwYkp1pqAapz44zX7BATI8z7Ra84RhqZv3l3zQMK539N8URVYSMJ9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
